services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3010:3010"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
